#!/usr/bin/env python3
"""Enforce Conventional Commits on a git ref range (Stage 3.4).

Replaces the Node.js commitlint dependency the original Stage 3.4 plan
implied: this template is Python-stdlib-only, so we inline a small,
transparent checker that mirrors the pieces of the
`Conventional Commits 1.0.0 <https://www.conventionalcommits.org/>`_
spec we actually want enforced for releases:

  - subject MUST match
    ``<type>(<scope>)?!?: <description>`` where ``<type>`` is one of
    the standard conventional-commits types (``feat``, ``fix``,
    ``chore``, ``docs``, ``style``, ``refactor``, ``perf``, ``test``,
    ``build``, ``ci``, ``revert``);
  - ``<description>`` is non-empty and the subject line is at most
    ``--max-subject`` chars (default 100);
  - merge commits (subject starts with ``Merge `` and they have more
    than one parent) are exempt — they're authored by GitHub, not us;
  - ``Revert "..."`` commits are exempt because the subject is forced
    by ``git revert`` and is allowed to mirror the reverted subject
    verbatim.

The checker is intentionally strict-by-default: any other shape is a
release blocker, and the failure message points at the exact commit
SHA + subject so authors can fix it with a rebase before re-pushing.

Stage 3.4 release-process invariant: this checker is invoked from CI
(see :file:`.github/workflows/ci.yml`) over the PR commit range
``${{ github.event.pull_request.base.sha }}..HEAD``. It does NOT
mutate refs, push tags, or run any other git side effect — fully
read-only, in line with the "no silent tag push" rule in
``core/release-process.md``.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys

DEFAULT_TYPES = (
    "feat",
    "fix",
    "chore",
    "docs",
    "style",
    "refactor",
    "perf",
    "test",
    "build",
    "ci",
    "revert",
)

# ``<type>(<scope>)?!?: <description>``
#
# - ``type`` matched as a full token so ``featx:`` does not pass.
# - ``(<scope>)`` optional, may be any non-paren chars.
# - ``!`` optional breaking-change marker.
# - ``: `` is REQUIRED (single space).
# - ``description`` is at least one non-whitespace char so empty
#   subjects are caught.
_SUBJECT_RE_TEMPLATE = (
    r"^(?P<type>{types})"
    r"(?P<scope>\([^)]+\))?"
    r"(?P<breaking>!)?: "
    r"(?P<description>\S.*)$"
)


def _build_subject_re(types):
    return re.compile(_SUBJECT_RE_TEMPLATE.format(types="|".join(map(re.escape, types))))


def _run_git(repo, *args):
    proc = subprocess.run(
        ["git", "-C", repo, *args],
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise SystemExit(
            f"git {' '.join(args)} failed: "
            f"{proc.stderr.strip() or proc.stdout.strip()}"
        )
    return proc.stdout


def _list_commits(repo, range_spec):
    """Return ``[(sha, subject, parent_count), ...]`` for ``range_spec``.

    Uses ``git log --format=%H%x09%P%x09%s`` so each row is a single
    line with tab separators. ``%P`` is the parent SHAs space-separated;
    we count tokens to detect merge commits without a second git call.
    """

    out = _run_git(
        repo,
        "log",
        "--format=%H%x09%P%x09%s",
        "--no-color",
        range_spec,
    )
    rows = []
    for line in out.splitlines():
        parts = line.split("\t", 2)
        if len(parts) < 3:
            continue
        sha, parents, subject = parts
        parent_count = len(parents.split()) if parents.strip() else 0
        rows.append((sha, subject, parent_count))
    return rows


def check_subject(subject, parent_count, subject_re, max_subject):
    """Return ``None`` if subject is acceptable, else a reason string.

    ``subject_re`` is the compiled :func:`_build_subject_re` for the
    configured type set.
    """

    # Merge commits (auto-generated by GitHub) and ``Revert "..."``
    # commits (auto-generated by ``git revert``) are exempt.
    if parent_count >= 2 and subject.startswith("Merge "):
        return None
    if subject.startswith('Revert "'):
        return None

    if len(subject) > max_subject:
        return f"subject longer than {max_subject} chars (got {len(subject)})"

    match = subject_re.match(subject)
    if not match:
        return (
            "subject does not match "
            "'<type>(<scope>)?!?: <description>' with allowed types"
        )
    if not match.group("description").strip():
        return "subject description is empty"
    return None


def check_range(repo, range_spec, types=DEFAULT_TYPES, max_subject=100):
    """Check every commit in ``range_spec``; return list of failures.

    Each failure is a dict with ``sha``, ``subject``, ``reason``. Empty
    list means the whole range is clean.
    """

    subject_re = _build_subject_re(types)
    failures = []
    for sha, subject, parent_count in _list_commits(repo, range_spec):
        reason = check_subject(subject, parent_count, subject_re, max_subject)
        if reason is not None:
            failures.append({"sha": sha, "subject": subject, "reason": reason})
    return failures


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="check-conventional-commits",
        description="Enforce Conventional Commits on a git ref range.",
    )
    parser.add_argument(
        "--repo",
        default=".",
        help="Git repository root (default: cwd).",
    )
    parser.add_argument(
        "--range",
        dest="range_spec",
        default=None,
        help=(
            "Git range to check (e.g. origin/main..HEAD). "
            "Default uses --from / --to or HEAD~..HEAD."
        ),
    )
    parser.add_argument("--from", dest="from_ref", default=None)
    parser.add_argument("--to", dest="to_ref", default="HEAD")
    parser.add_argument("--max-subject", type=int, default=100)
    parser.add_argument(
        "--allow-empty",
        action="store_true",
        help="Exit 0 when the resolved range yields zero commits.",
    )
    args = parser.parse_args(argv)

    if args.range_spec:
        range_spec = args.range_spec
    elif args.from_ref:
        range_spec = f"{args.from_ref}..{args.to_ref}"
    else:
        # ``HEAD~..HEAD`` covers the just-created commit on a feature
        # branch when nothing else is available. The CI workflow is
        # expected to pass an explicit range; this default is for
        # local invocations.
        range_spec = "HEAD~..HEAD"

    failures = check_range(
        args.repo,
        range_spec,
        max_subject=args.max_subject,
    )
    commits_seen = _list_commits(args.repo, range_spec)

    if not commits_seen:
        if args.allow_empty:
            sys.stdout.write(f"PASS: no commits in range {range_spec}\n")
            return 0
        sys.stderr.write(
            f"FAIL: no commits found in range {range_spec} "
            f"(pass --allow-empty to skip empty ranges)\n"
        )
        return 2

    if not failures:
        sys.stdout.write(
            f"PASS: {len(commits_seen)} commit(s) in {range_spec} "
            f"match Conventional Commits.\n"
        )
        return 0

    sys.stderr.write(
        f"FAIL: {len(failures)} commit(s) in {range_spec} "
        f"violate Conventional Commits:\n"
    )
    for failure in failures:
        sys.stderr.write(
            f"  {failure['sha'][:12]} {failure['subject']!r} "
            f"-> {failure['reason']}\n"
        )
    sys.stderr.write(
        "Allowed shape: '<type>(<scope>)?!?: <description>' where "
        "<type> is one of " + ", ".join(DEFAULT_TYPES) + ".\n"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
