#!/usr/bin/env bash
# Migration regression test for 0.9.0 -> 0.10.0.
#
# Builds a genuine 0.9.0 fixture from the canonical 0.3.0 baseline via
# multi-hop sync, then validates the constitution split (PR-3a/PR-3b):
#   - .agent/constitution.md is installed,
#   - .agent/rulebase.md is patched with a pointer (idempotent),
#   - .agent/workflows/rule-evolution-workflow.md gains the Out-Of-Scope
#     section,
#   - manifest bumps to 0.10.0 and canonical_files lists the constitution,
#   - the generated validator passes,
#   - re-apply is a no-op (idempotent).
#
# The test relies on `git show v0.9.0:...` for the source baseline, so CI
# checkouts must use fetch-depth: 0 (already enforced in
# .github/workflows/ci.yml::migration-fixtures).

set -euo pipefail

root="$(git rev-parse --show-toplevel)"
work_root="$(mktemp -d /tmp/migration-0.10.0.XXXXXX)"

ephemeral_v0100_created="0"

cleanup() {
  if [ "$ephemeral_v0100_created" = "1" ]; then
    git -C "$root" tag -d v0.10.0 >/dev/null 2>&1 || true
  fi
  rm -rf "$work_root"
}
trap cleanup EXIT

assert_file_contains() {
  path="$1"
  needle="$2"
  desc="$3"
  if grep -qF -- "$needle" "$path"; then
    printf 'PASS: %s\n' "$desc"
  else
    printf 'FAIL: %s\n  file=%s\n  needle=%s\n' "$desc" "$path" "$needle" >&2
    exit 1
  fi
}

assert_file_absent() {
  path="$1"
  desc="$2"
  if [ ! -e "$path" ]; then
    printf 'PASS: %s\n' "$desc"
  else
    printf 'FAIL: %s\n  unexpected path exists\n' "$desc" >&2
    exit 1
  fi
}

ensure_previous_release_tag() {
  if git -C "$root" rev-parse --verify --quiet "v0.9.0^{commit}" >/dev/null; then
    return 0
  fi
  printf 'SKIP: v0.9.0 tag is missing; cannot build the 0.9.0 regression fixture.\n'
  exit 0
}

ensure_current_release_tag() {
  if git -C "$root" rev-parse --verify --quiet "v0.10.0^{commit}" >/dev/null; then
    return 0
  fi
  # Guard: the migration sources for 0.10.0 must be committed before tagging
  # the ephemeral v0.10.0.  If any of these paths show as dirty we abort with
  # SKIP rather than tagging an inconsistent tree.
  if [ -n "$(git -C "$root" status --short -- \
    CHANGELOG.md \
    core/constitution.template.md \
    core/hooks/README.md \
    core/hooks/pre-tool-use-rulebase-guard.py.template \
    core/manifest.template.json \
    core/migrations/0.10.0 \
    core/rulebase.template.md \
    core/workflows/rule-evolution-workflow.md \
    scripts/bootstrap-request.sh \
    scripts/lib/validate_agent_system.py \
    .claude-plugin/plugin.json \
    .claude-plugin/marketplace.json)" ]; then
    printf 'SKIP: v0.10.0 tag is missing and 0.10.0 migration sources are not committed yet.\n'
    exit 0
  fi
  git -C "$root" tag v0.10.0
  ephemeral_v0100_created="1"
}

remove_pycache() {
  dir="$1"
  find "$dir" -type d -name __pycache__ -prune -exec rm -rf {} +
}

setup_090_fixture() {
  fixture_dir="$work_root/clean-from-0.9.0"
  cp -a "$root/tests/migrations/0.3.0/after/." "$fixture_dir/" >&2
  (
    cd "$fixture_dir"
    git init -q
    git -c user.email=t@t -c user.name=Test add .
    git -c user.email=t@t -c user.name=Test commit -q -m "fixture@0.3.0"
  ) >&2

  # Multi-hop to 0.9.0.  agent-eval.sh is regenerated by 0.8.x migrations and
  # gate candidate insertion may produce a marker block that differs from the
  # 0.3.0 baseline; --accept-theirs lets that conflict resolve cleanly without
  # affecting the constitution-split surface we care about.
  AGENT_SYNC_NOW=2026-05-02T00:00:00Z \
    "$root/scripts/agent-sync.sh" --multi-hop --target "$fixture_dir" --to 0.9.0 --apply \
      --accept-theirs scripts/agent-eval.sh >&2

  remove_pycache "$fixture_dir"
  (
    cd "$fixture_dir"
    git -c user.email=t@t -c user.name=Test add .
    git -c user.email=t@t -c user.name=Test commit -q -m "fixture@0.9.0"
  ) >&2

  # Pre-state assertions: the 0.9.0 fixture must NOT yet contain the
  # constitution, the rulebase must NOT yet contain the pointer, and the
  # rule-evolution workflow must NOT yet have the Out-Of-Scope section.
  assert_file_contains "$fixture_dir/.agent/manifest.json" '"template_version": "0.9.0"' \
    "[setup] manifest template_version=0.9.0" >&2
  assert_file_absent "$fixture_dir/.agent/constitution.md" \
    "[setup] constitution absent before 0.10.0" >&2
  if grep -qF -- ".agent/constitution.md" "$fixture_dir/.agent/rulebase.md"; then
    printf 'FAIL: [setup] rulebase already references constitution before 0.10.0 sync\n' >&2
    exit 1
  fi
  printf 'PASS: [setup] rulebase has no constitution pointer before 0.10.0\n' >&2
  if grep -qF -- "## Out Of Scope" "$fixture_dir/.agent/workflows/rule-evolution-workflow.md"; then
    printf 'FAIL: [setup] rule-evolution-workflow already has Out-Of-Scope before 0.10.0 sync\n' >&2
    exit 1
  fi
  printf 'PASS: [setup] rule-evolution-workflow has no Out-Of-Scope before 0.10.0\n' >&2

  printf '%s\n' "$fixture_dir"
}

ensure_previous_release_tag
ensure_current_release_tag
fixture="$(setup_090_fixture)"

AGENT_SYNC_NOW=2026-05-03T00:00:00Z \
  "$root/scripts/agent-sync.sh" --target "$fixture" --to 0.10.0 --apply

# Manifest assertions.
assert_file_contains "$fixture/.agent/manifest.json" '"template_version": "0.10.0"' \
  "[clean-from-0.9.0] manifest template_version=0.10.0"
assert_file_contains "$fixture/.agent/manifest.json" '"synced_to_template_version": "0.10.0"' \
  "[clean-from-0.9.0] manifest synced_to=0.10.0"
assert_file_contains "$fixture/.agent/manifest.json" '".agent/constitution.md"' \
  "[clean-from-0.9.0] manifest canonical_files lists constitution"
assert_file_contains "$fixture/.agent/sync-log.md" "Sync to 0.10.0" \
  "[clean-from-0.9.0] sync log appended"

# Constitution file installed with required policy phrases.
assert_file_contains "$fixture/.agent/constitution.md" \
  "NO COMPLETION CLAIMS WITHOUT FRESH VERIFICATION EVIDENCE" \
  "[clean-from-0.9.0] constitution includes discipline gates"
assert_file_contains "$fixture/.agent/constitution.md" \
  "Forbidden Without Explicit Human Approval" \
  "[clean-from-0.9.0] constitution includes forbidden section"
assert_file_contains "$fixture/.agent/constitution.md" \
  "Database & Migration Invariants" \
  "[clean-from-0.9.0] constitution includes database invariants"

# Rulebase pointer patched in idempotently.
assert_file_contains "$fixture/.agent/rulebase.md" ".agent/constitution.md" \
  "[clean-from-0.9.0] rulebase points to constitution"
assert_file_contains "$fixture/.agent/rulebase.md" \
  "Amendments require explicit human approval" \
  "[clean-from-0.9.0] rulebase pointer mentions explicit approval"

# Rule-evolution workflow gains Out Of Scope section.
assert_file_contains "$fixture/.agent/workflows/rule-evolution-workflow.md" \
  "## Out Of Scope" \
  "[clean-from-0.9.0] rule-evolution workflow Out-Of-Scope section installed"
assert_file_contains "$fixture/.agent/workflows/rule-evolution-workflow.md" \
  ".agent/constitution.md" \
  "[clean-from-0.9.0] rule-evolution workflow excludes constitution"

# Generated validator (now constitution-aware) passes against the migrated
# repo.
AGENT_ROOT="$fixture" bash "$fixture/scripts/agent-validate.sh" >/tmp/migration-0.10.0-validate.out
assert_file_contains "/tmp/migration-0.10.0-validate.out" "All validation checks passed." \
  "[clean-from-0.9.0] generated validator passes after constitution split"

remove_pycache "$fixture"
(
  cd "$fixture"
  git -c user.email=t@t -c user.name=Test add .
  git -c user.email=t@t -c user.name=Test commit -q -m "first 0.10.0 apply"
)

# Idempotent re-apply: no working-tree changes.
AGENT_SYNC_NOW=2026-05-03T00:00:00Z \
  "$root/scripts/agent-sync.sh" --target "$fixture" --to 0.10.0 --apply

if [ -n "$(git -C "$fixture" status --short)" ]; then
  git -C "$fixture" status --short
  printf 'FAIL: [clean-from-0.9.0] re-apply produced changes\n' >&2
  exit 1
fi
printf 'PASS: [clean-from-0.9.0] idempotent re-apply\n'

printf '\nAll 0.10.0 migration assertions passed.\n'
