# Bootstrap: render token map, copy/render helpers (sourced early; trap set by orchestrator).

cleanup_render_token_map() {
  if [ -n "$render_token_map_file" ] && [ -f "$render_token_map_file" ]; then
    rm -f "$render_token_map_file"
  fi
}

record_written() {
  written_files="${written_files}
- $1"
}

record_skipped() {
  skipped_files="${skipped_files}
- $1"
}

ensure_dir() {
  dir="$1"
  if [ "$dry_run" = "1" ]; then
    log "DRY-RUN mkdir -p $dir"
  else
    mkdir -p "$dir"
  fi
}

copy_file() {
  src="$1"
  dest="$2"
  mode="${3:-}"

  [ -f "$src" ] || die "source file missing: $src"

  if [ -e "$dest" ] && [ "$force" != "1" ]; then
    log "SKIP existing $dest"
    record_skipped "$dest"
    return
  fi

  ensure_dir "$(dirname "$dest")"
  if [ "$dry_run" = "1" ]; then
    log "DRY-RUN copy $src -> $dest"
  else
    cp "$src" "$dest"
    if [ -n "$mode" ]; then
      chmod "$mode" "$dest"
    fi
  fi
  record_written "$dest"
}

create_render_token_map() {
  if ! command -v python3 >/dev/null 2>&1; then
    die "python3 is required to render Agent Bootstrap templates"
  fi

  render_token_map_file="$(mktemp -t agent-render.XXXXXX.json)"
  TOKEN_MAP_FILE="$render_token_map_file" \
  INSTANTIATED_AT_ISO8601="$generated_at" \
  TEMPLATE_VERSION="$template_version" \
  FEATURES_ENABLED_JSON_ARRAY="$features_enabled_json" \
  LLM_TOOL_USED="bootstrap-request.sh skeleton; agent completion pending" \
  REPO_NAME="$project_name" \
  AGENT_BOOTSTRAP_TEMPLATE_REPO_URL_OR_PATH="$source_template" \
  PROJECT_NAME="$project_name" \
  PRIMARY_LANGUAGE="$primary_language" \
  PACKAGE_MANAGER_OR_NOT_APPLICABLE="$package_manager" \
  FRAMEWORK_1="not confirmed" \
  DEPLOYMENT_TARGET_1="not configured" \
  CONFIGURED_OR_NOT_CONFIGURED="not configured" \
  CHANGED_GATE_COMMANDS="not configured" \
  FAST_GATE_COMMANDS="not configured" \
  FRONTEND_GATE_COMMANDS="not configured" \
  BACKEND_GATE_COMMANDS="not configured" \
  SHARED_GATE_COMMANDS="not configured" \
  E2E_GATE_COMMANDS="not configured" \
  FULL_GATE_COMMANDS="not configured" \
  SECURITY_GATE_COMMANDS="not configured" \
  RELEASE_GATE_COMMANDS="not configured" \
  NOT_CONFIGURED_GATE_OR_EMPTY_ARRAY="not configured" \
  ONE_PARAGRAPH_DESCRIPTION_OF_THE_PRODUCT_OR_LIBRARY="Bootstrap skeleton generated by script. Complete repo-specific description from checked-in evidence before deleting .agent/bootstrap-pending.md." \
  python3 - <<'PY'
import json
import os
from pathlib import Path

token_file = Path(os.environ["TOKEN_MAP_FILE"])
tokens = {
    key: value
    for key, value in os.environ.items()
    if key
    in {
        "INSTANTIATED_AT_ISO8601",
        "TEMPLATE_VERSION",
        "FEATURES_ENABLED_JSON_ARRAY",
        "LLM_TOOL_USED",
        "REPO_NAME",
        "AGENT_BOOTSTRAP_TEMPLATE_REPO_URL_OR_PATH",
        "PROJECT_NAME",
        "PRIMARY_LANGUAGE",
        "PACKAGE_MANAGER_OR_NOT_APPLICABLE",
        "FRAMEWORK_1",
        "DEPLOYMENT_TARGET_1",
        "CONFIGURED_OR_NOT_CONFIGURED",
        "CHANGED_GATE_COMMANDS",
        "FAST_GATE_COMMANDS",
        "FRONTEND_GATE_COMMANDS",
        "BACKEND_GATE_COMMANDS",
        "SHARED_GATE_COMMANDS",
        "E2E_GATE_COMMANDS",
        "FULL_GATE_COMMANDS",
        "SECURITY_GATE_COMMANDS",
        "RELEASE_GATE_COMMANDS",
        "NOT_CONFIGURED_GATE_OR_EMPTY_ARRAY",
        "ONE_PARAGRAPH_DESCRIPTION_OF_THE_PRODUCT_OR_LIBRARY",
    }
}
token_file.write_text(json.dumps(tokens, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")
PY
}

render_template() {
  src="$1"
  dest="$2"

  copy_file "$src" "$dest"
  [ "$dry_run" = "1" ] && return
  [ -f "$dest" ] || return

  python3 "$TEMPLATE_ROOT/scripts/lib/render_template.py" \
    "$dest" \
    "$render_token_map_file" \
    --fallback "not confirmed - complete .agent/bootstrap-pending.md"
}
